stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t my-react-app:latest .
    - docker save -o my-react-app.tar my-react-app:latest
    - scp my-react-app.tar $SERVER_USER@$SERVER_HOST:/path/to/destination

deploy:
  stage: deploy
  script:
    - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "
      docker load -i /path/to/destination/my-react-app.tar
      docker stop my-react-app || true
      docker rm my-react-app || true
      docker run -d --name my-react-app -p 80:80 my-react-app:latest"
  only:
    - main