stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t my-react-app:latest .
    - docker tag my-react-app:latest registry.gitlab.com/your-namespace/my-react-app:latest
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker push registry.gitlab.com/your-namespace/my-react-app:latest

deploy:
  stage: deploy
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "
      docker pull registry.gitlab.com/your-namespace/my-react-app:latest
      docker stop my-react-app || true
      docker rm my-react-app || true
      docker run -d --name my-react-app -p 80:80 registry.gitlab.com/your-namespace/my-react-app:latest
    "
  only:
    - main