name: Deploy React App to Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

    - name: Build Docker image
      run: docker build -t my-react-app .

    - name: Save Docker image
      run: docker save -o my-react-app.tar my-react-app

    - name: Upload Docker image to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        source: "my-react-app.tar"
        target: "/path/to/destination"

    - name: Load and run Docker image on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          docker load -i /path/to/destination/my-react-app.tar
          docker stop my-react-app-container || true
          docker rm my-react-app-container || true
          docker run -d -p 80:80 --name my-react-app-container my-react-app